### PR TITLE
FOOTER LIVE SITE FIX

### PR DESCRIPTION
**Pull request by jzhzhang66**
Previously there was an issue adding the footer to the live site because of the folder structure / where the mailchimp plugin was installed. This PR fixes that!!

Changelist:

- Abstracted out mailchimp plugin into shared package.json + moved mailing list signup to shared ui from the main site 
- Made background vw 100 to fix the below issue lMAOOOO 
Screenshot 2022-11-20 at 10 58 41 PM

Screenshots & Screencasts:

footer shows up on main site + live site deploys (ss below) + build passes without errors
Screenshot 2022-11-20 at 10 59 46 PM

### CODE REVIEW

**Review by jhylisa666 — COMMENTED** [review]
GREAT JOB BOSS!!!
Just wondering, is it intended for the footer to show up at the top?
Screen Shot 2022-11-22 at 9 39 03 PM

**Comment by jzhzhang66** [comment]
@jhylisa666 Good q!! Yes - the content added in the middle will push it to the bottom! We want to eventually switch the way we're rendering the bg over to the way it's being done in the main site which would cause the footer to go to the bottom. But for some reason doing it that way causes the entire page to be blank on the live site so I need to investigate that more! This is a fix for now until I figure out what's going wrong with that hahaha

**Review by deanframe — APPROVED** [review]
nice LGTM!

(lol so many merge conflicts rippp)

**Review by jhylisa666 — APPROVED** [review]
OKKK BOSSSS

**Pull request merged**
