### PR TITLE
Error page

### LINKED ISSUE #45: 404 page
- [ ] Implement the mobile + desktop version for the 404 page (see [Figma] (https://www.figma.com/file/GSDe4OZqUkyYcPSIVDI3qD/2023-Website-Designs?node-id=1272%3A1816))
- [ ] You can probably just export the entire background (everything except text + button) as an svg

Screen Shot 2022-10-26 at 5 55 14 PM

Screen Shot 2022-10-26 at 9 05 30 PM

### PR DESCRIPTION
**Pull request by jhylisa666**
Made 404 error page for main site
Fixes #45

Changelist:
- responsive 404 error page

Notes:
- didn't pin button on the ship because don't know how to. It just keeps on moving when I shrink the screen size, so instead I just aligned it with the 'Let's keep exploring'. 
- interesting white space at the bottom for tablet large. Desktop background dimensions don't quite fit, should I change it to mobile background even for tablet large?

Screenshots & Screencasts:

https://user-images.githubusercontent.com/92692037/199035405-1e42896f-e122-4fe2-8e8d-93773070c435.mov

### CODE REVIEW

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
Hey Lisa!!! Nice job!

We actually had this issue with the whitspace on the main site too. This week, to fix it I changed our site to use background-image and background-size: cover. See https://github.com/HackBeanpot/mono-repo/pull/47/files

See my PR here - let's switch to this approach to fix the issue. I can't think of a easy way to align the button on the boat rn either... idk if @Dhivas-Sugumar has any ideas but otherwise we can just keep it like this it's fine haha

**Comment by jzhzhang66** [comment]
Screen Shot 2022-11-01 at 5 48 56 PM

The deploy preview looks kinda funny - can u look into this + fix it? Maybe the background thing will fix it @jhylisa666

**Review by Dhivas-Sugumar — COMMENTED** [review]
I am not entirely sure how to get it aligned. css is not my forte.

**Review by Dhivas-Sugumar — APPROVED** [review]
LGTM! Great work Lisa!

**Review by jzhzhang66 — APPROVED** [review]
LGTM

**Pull request merged**
