### PR TITLE
Sponsor Testimonial Section

### LINKED ISSUE #200: [Feature] Sponsor Testimonial Section
### _**MERGE INTO `sponsor-us-dev-branch` and not `main`**_

Implement new sponsor testimonial [design](https://www.figma.com/file/GSDe4OZqUkyYcPSIVDI3qD/2023-Website-Designs?type=design&node-id=10-79&mode=design&t=Xd6qbJEnm2ZCZfdG-0)!!!

Image

- [x] Update implementation to take in  testimonial data in the `TestimonialSection` component
- [x] Add an `isSponsor` prop to `TestimonialSection`
- [x] Use the new `isSponsor` prop to change between sponsor-page styles and main-page styles
- [x] Add testimonial component to sponsor page

Review by @kzeng24 @zhangcry @jmsargent10

### PR DESCRIPTION
**Pull request by vonbuelow**
fixes #200 

Sponsor testimonial design on Sponsor Us page

Changelist:

- `TestimonialSection `component takes in testimonial data and added `isSponsor `prop
- added `sponsorTestimonialData `to `data.ts`
- added image to `aboutSectionData` & `sponsorTestimonialData `to `data.ts` 
- ternary operators using `isSponsor `prop to switch styles between main & sponsor page **_only desktop_
- updated testimonial component to the sponsor-page 

Notes:
- Wood Mackenzie logo changed from Figma design. Will update before merge
image

Tested:

- localhost

Screenshots & Screencasts:

Sponsor Testimonials 
image

### CODE REVIEW

**Review by kzeng24 — CHANGES_REQUESTED** [review]
Looks great!! Some feedback I have are:
1. make sure to change the PR settings such that you merge into sponsor-us-dev-branch instead of main
2. I noticed that in Figma, the chosen testimonial number has a circle highlight in the background (like this below), while the numbers from your code are yellow-colored. Is there a reason for this change in style? 
Screenshot 2023-07-24 at 10 35 52 PM <br/>
3. The images for each company are a little blurry - is there a way to make them have a higher resolution?

**Comment by mike10911** [comment]
@kzeng24 The change in testimonial pagination styles will be done in a future ticket!

**Review by kzeng24 — CHANGES_REQUESTED** [review]
Just noticed another thing! From the Figma, it seems that the sponsor position / company label should be a bit more bolded so that it stands out from their testimonial quote. Here's a more close-up screenshot - I hope I'm not going crazy by the subtle difference XD
Screenshot 2023-07-24 at 10 52 46 PM

**Comment by kzeng24** [comment]
Lastly, I think the font for each sponsor's name should be a bit more curvy and stronger:

Figma version
Screenshot 2023-07-24 at 10 59 38 PM
Vs. Local version
Screenshot 2023-07-24 at 10 59 48 PM

**Review by kzeng24 — APPROVED** [review]
Looks fantastic!! :)

**Review by jmsargent10 — APPROVED** [review]
LGTM!

**Pull request merged**
