### PR TITLE
Added base case to timer "00:00:00"

### LINKED ISSUE #175: Base Case for Time Remaining Clock
To keep track of the time until the hackathon starts, visiting users can find the time remaining countdown at the bottom of the live site (live.hackbeanpot.com) and the main site (live.hackbeanpot.com). The clock can be found in the `TimeRemaining.tsx` component located in the `share-ui` directory of the repository. Unfortunately, the countdown has already passed the event date, resulting in a negative clock.

### Example:

Screen Shot 2023-05-08 at 10 02 58 PM

### You can help by:

- [ ] Creating a base case for the countdown so that when the given date has elapsed, it reads 00:00:00:00

### PR DESCRIPTION
**Pull request by Mandy-cyber**
<Summary line - Added base case to livesite timer>

Fixes #175 .

Changelist:

- Added conditional to useEffect hook to check when the time difference is <= 0
- Appended zeroes onto timer text if the value was 0

Screenshots & Screencasts:
image

### CODE REVIEW

**Review by surbhi-gulati — APPROVED** [review]
LGTM!!! Great work :) Before you merge in, a couple guidelines idk if we covered at the tech orientation:

1. could you fix the comment to correctly link up issue 175 (https://github.com/HackBeanpot/mono-repo/issues/175) in the fixes line? This pairs it up with the bug properly for when we look back at commit history. 
2. hit "squash and merge" instead of just merge to combine all your commits in this PR in to one concise commit

**Review by zhangcry — CHANGES_REQUESTED** [review]
From @mike10911 @zhangcry 
Great work on the ticket! Awesome use of detailed commit messages.

One minor change and this can get merged:
- In order to give more meaningful names to variables, we should change the d, h, m, and s to days, hours, mins/minutes, secs/seconds

**Review by mike10911 — APPROVED** [review]
APPROVED. GOOD TO MERGE AFTER @zhangcry 's changes are resolved

**Review by zhangcry — COMMENTED** [review]
lgtm!!

**Review by zhangcry — APPROVED** [review]
accidentally just left a comment, should be good to go!!

**Pull request merged**
