### PR TITLE
Cz am/updating sponsor landing

### LINKED ISSUE #323: Update Landing page
[Designs](https://www.figma.com/file/ONkXtJcw5iJL5Az7Mmi64S/Main-Site-Wireframes?type=design&node-id=323-463&mode=design&t=PIjtncHuQ6MnFP4i-0)

Update sponsor us landing page to reflect the theme refresh!

AC:

- [ ] Total responsiveness
- [ ] Light and dark mode

Image

@mike10911 @helenm1

### PR DESCRIPTION
**Pull request by alyssamui**
Update Sponsor Us Landing Page Section

Fixes #323 .

Changelist:
- Update sponsor us landing page to reflect the theme refresh!
- Total responsiveness
- Light and dark mode

Screenshots & Screencasts:

https://github.com/HackBeanpot/mono-repo/assets/82426237/864d368a-07cd-498d-980c-2d56b8e4ef77

### CODE REVIEW

**Review by helenm1 — APPROVED** [review]
LGTM

**Review by mike10911 — CHANGES_REQUESTED** [review]
SO SLAYYY! Just one nitpick

Screenshot 2024-02-05 at 4 33 57 PM
The jellyfish seems to get cut off at smaller screen sizes. Let's move this a bit to the right.

**Comment by alyssamui** [comment]
> SO SLAYYY! Just one nitpick
> 
> Screenshot 2024-02-05 at 4 33 57 PM The jellyfish seems to get cut off at smaller screen sizes. Let's move this a bit to the right.


what dimensions are you seeing this at?

**Review by mike10911 — APPROVED** [review]
LGTM

**Pull request merged**
