### PR TITLE
Updated Mentor Section

### LINKED ISSUE #321: [Feature] Update Mentor Section
[Designs](https://www.figma.com/file/NzIlQyV6bXIksv9SyIFjj3/Live-Site-Wireframes?type=design&node-id=158-743&mode=design&t=7GS8hzqiKkaMniJI-0)

AC:

- [ ] Update mentor section to reflect design
- [ ] Ensure desktop responsiveness
- [ ] Light and dark mode

Image

@kzeng24 @mike10911

### PR DESCRIPTION
**Pull request by Aaryan1203**
<Summary line - One sentence describing your intended set of changes>

Fixes #321 

Changelist:

- Updated the mentor section to fit the new styles
- Updated the buttons so they are now arrows instead of the cactus buttons
- Removed the MLH banner from the live site
- Added mermaid

Screenshots & Screencasts:
image
image

### CODE REVIEW

**Review by mike10911 — CHANGES_REQUESTED** [review]
Looks great!

In regards to the mermaid, have you tried using `width: x%`?

Also when you took out the banner you also took out the nav bar which we still want on the live site!

**Review by mike10911 — CHANGES_REQUESTED** [review]
AMAZING JOB Debugging!!! This all looks good, I have two comments, and then it should be good to merge.

- The mermaid should be farther to the right to reflect the design.
- The mermaid's tail is cut off, please export it in its entirety!

**Review by kzeng24 — CHANGES_REQUESTED** [review]
Looks great!!

One thing that I noticed was that when I shrink the screen to maybe tabloid / smaller desktop view, it only shows one arrow 

Screenshot 2024-01-13 at 2 34 58 AM

**Review by mike10911 — APPROVED** [review]
lgtm

**Review by kzeng24 — APPROVED** [review]
Approved!

**Pull request merged**
