### PR TITLE
Removing Elapsed Events

### LINKED ISSUE #178: Removing Elasped Events
In the "Event Calendar" section of the main site (hackbeanpot.com) and in the main-site directory under components/event-calendar-section, all of the events have elapsed but the base case component is not displayed to let the user know that there are no more events. See [here](https://www.figma.com/file/GSDe4OZqUkyYcPSIVDI3qD/2023-Website-Designs?type=design&node-id=10-79&t=Kf1QZMjkinZfGxfl-0) for the design example

### Current State:
Screen Shot 2023-05-08 at 11 18 46 PM

### Your Job is to:
- [ ] Conditionally render the base case component when all events have elapsed based on the design

### PR DESCRIPTION
**Pull request by zhangcry**
<Summary line - One sentence describing your intended set of changes>

Fixes <https://github.com/HackBeanpot/mono-repo/issues/178>.

Changelist:

- Commented out elapsed events.
- Added "no events to display" component.

Notes:

- Original code didn't allow for conditional rendering, so in the meantime this is the immediate fix.
- For future changes, ideally events would be mapped and time/date would determine how it is rendered and including if "no events to display" will be displayed.

Tested:

- Ran main site locally to check if changes are reflected on desktop and non desktop screen widths.

Screenshots & Screencasts:
Current main site
Screenshot 2023-05-14 at 12 05 40 AM

Main site with changes
Screenshot 2023-05-14 at 12 09 00 AM

### CODE REVIEW

**Comment by mike10911** [comment]
Originally, I thought that the component was mapped and changed colors based on if the time has elapsed but it seems everything was hard coded. For best practices, we would have to revamp the whole section in order to implement the conditional rendering I mentioned in #178  along with implementing a useState hook which is a lot for a first ticket! So for now we will just comment out the other events and have the "No events to display" component showing. Component reworking will be in a future ticket!

**Comment by mike10911** [comment]
Screen Shot 2023-05-14 at 2 16 12 PM

### Centered the text and gave a bit more padding!

**Review by NelsonDong41 — COMMENTED** [review]
looks good !

**Review by Aaryan1203 — COMMENTED** [review]
lgtm!

**Pull request merged**
