### PR TITLE
Housekeeping

### LINKED ISSUE #40: Housekeeping
- [ ] The background is initially flashing to the mobile version when the page loads - click on this link to see https://mono-repo-six.vercel.app/ . Fix this issue - a possible solution is you need to set the initial state to be window.width (david's hunch LOL) 
- [ ] Footer is looking too short at this width - increase the height or move bottom content up Screen Shot 2022-10-11 at 11 42 59 PM
- [ ] Update spacing between sections to be more similar to design
- [ ] Increase button size on mobile

### PR DESCRIPTION
**Pull request by jzhzhang66**
<Summary line - One sentence describing your intended set of changes>

Fixes #40.

Changelist:
- Fix the issue with being able to scroll past the footer / background was too short
- Fix background loading issue seen here by adding in a loading state so that the screen is blank when loading the page https://mono-repo-six.vercel.app/
- Fix this footer issue Screen Shot 2022-10-30 at 10 15 33 PM
- Reordered sections based on suggestions by @yanDavid21 
- Enlarged calendar section to match sizing of other sections 
- Increase button size on mobile to be more similar to proportions on figma 
- Fixed issue with go workshop hanging off section at larger screensizes Screen Shot 2022-10-30 at 10 18 13 PM
- Removed button from covid section (per request by david since we don't have anything to link it to)
- Updated some of the copy to be more desert themed 
- Updated when go + security workshops are gonna be

Tested:

- Chrome + safari

### CODE REVIEW

**Comment by deanframe** [comment]
Thanks for this! Seeing some issues on chrome on my end:
1. can we move the options on the header to the left? the scrollbar is making it seem squished
image
2. testimonials section cut off on the sides
image
3. past photos section overflows to the right slightly
lmk if youre also seeing these!

**Comment by jzhzhang66** [comment]
@deanframe yes I will fix 1) !! The testimonials are supposed to be cut off (see design) and then for 3) I'm not seeing this but david also brought this up so I've been pushing stuff to see if it'll fix it

**Review by deanframe — APPROVED** [review]
LGTM will take a look at the past photos issue this week!

**Review by jhylisa666 — CHANGES_REQUESTED** [review]
Screen Shot 2022-11-01 at 11 48 55 PM
1. U WICKED SMAAAART BOSS. GOOD JOB
2. I think for tablet or mobile sizes, there seems to be a weird fault line in the dark mode in the landing section. Not sure if that was intended
3. Is there a reason that Safety First is sort of like a different header from the rest? I personally think it looks better if they are all the same font/size but if that's acc
Screen Shot 2022-11-01 at 11 52 29 PM
ording to design it's all good!!
4. Events Calender Tablet not sure if the inner dark green boxes are centered.
BUT YAAAA THANKS BOSS FOR DOING THIS AND CLEAN UP ALL OUR STUFF

**Comment by jzhzhang66** [comment]
@deanframe moved header to the left!

**Comment by jzhzhang66** [comment]
@jhylisa666 thanks for the awesome feedback!!! I fixed the green centering and also the safety first header! I brought up the line to Sarah before since it's on the Figma too but I don't think she knows where its coming from - if we can figure out how to fix it on figma lets def pull it into a future sprint!

**Review by jhylisa666 — APPROVED** [review]
LGTM BOSSS

**Pull request merged**
