### PR TITLE
Feature/update sponsor testimonial

### LINKED ISSUE #376: [Feature] Sponsor Us Testimonial Updates
- decrease opacity for non selected sponsor testimonials to match [design](https://www.figma.com/design/ONkXtJcw5iJL5Az7Mmi64S/Main-Site-Wireframes?node-id=323-463&t=4PPy4nWX7iQQVUp1-0)
- for mobile view: reduce top and bottom spacing as well as spacing between text sections of testimonial card

Image
Image

AC:
- [x] ensure responsiveness on all screen sizes
- [x] ensure section matches design

Reviewers:
- @jmsargent10 @Lucas-Dunker @achen32

### PR DESCRIPTION
**Pull request by agonzalez22**
updated Sponsor Us testimonials to reflect design changes!

Fixes #376.

Changelist:

- Changed font color & text alignment for sponsor testimonial cards.
- changed card background color and adjusted opacity for left and right cards in the carousel. 

Tested:

- visual testing 
- checked different breakpoints in the browser

Screenshots & Screencasts:
image
image

### CODE REVIEW

**Review by Lucas-Dunker — COMMENTED** [review]
Screenshots look great! Where would I find this section on the site preview? While the testimonials section has been renamed to "Sponsor Testimonials", I don't see any content changes

**Comment by agonzalez22** [comment]
> Screenshots look great! Where would I find this section on the site preview? While the testimonials section has been renamed to "Sponsor Testimonials", I don't see any content changes

its on the /sponsor-us path, wasn't sure if I was supposed to link it! @Lucas-Dunker

**Review by jmsargent10 — CHANGES_REQUESTED** [review]
looks great! just a few notes:
- we want to ensure that the regular testimonials section title is unchanged (right now it also says sponsor testimonials!)
- there looks to be some merge conflicts, as well as some changes being tracked in files from previous tickets, so ensure that these are resolved before merging

**Review by jmsargent10 — APPROVED** [review]
LGTM!!

**Pull request merged**
