### PR TITLE
Update past projects with 2024 winners

### PR DESCRIPTION
**Pull request by Lucas-Dunker**
Refresh the HBP site with past projects from the past year! 

Feature #363 

Changelist:
- Update site with 2024 project winners + devpost links 

Notes:
- Data obtained from [here](https://docs.google.com/spreadsheets/d/18xMqJeaVeAtFt5CDhe4so5A9XZfRAqDpV0xyFaEif0g/edit#gid=0)
- Only projects with the non-red names were added, but we can definitely add the other projects (and omit the missing names) if we want to! 

Tested:

- Visual testing (see screenshots below) 

Screenshots & Screencasts:

- Desktop:
image
image

- Mobile:
image

### CODE REVIEW

**Review by achen32 — APPROVED** [review]

**Review by mike10911 — APPROVED** [review]
SLAYY LGTM

**Review by jmsargent10 — CHANGES_REQUESTED** [review]
hi guys! the updates look great! I updated the award winning projects file, so the ones that were red are now green, and I also updated one of the names for the perfect pantry to reflect what was on the 2024 applications google sheet. once these updates are in lmk and I will approve!

**Review by NelsonDong41 — APPROVED** [review]
LGTM!

**Review by jmsargent10 — APPROVED** [review]
LGTM!

**Pull request merged**
