### PR TITLE
Live Site Gradient Updates

### PR DESCRIPTION
**Pull request by zhangcry**
# <Updated Live Site Landing Section Gradient to be Seamless>

### ▶ Changelist:

- Created a night and day version of sand file for live site landing section
- Updated the color of last stopper to blend into color of site background
- Added conditional rendering for night and day

### 🧪 Testing:

- Visual testing in both day and night mode
- Visual testing for different resolutions

### 🎥 Screenshots & Screencasts:

Screenshot 2024-06-02 at 9 42 21 PM
Screenshot 2024-06-02 at 9 42 30 PM

### CODE REVIEW

**Review by jmsargent10 — CHANGES_REQUESTED** [review]
hi Crystal, great work! the logic looks great, however i think you may need to re-export the image for the dark mode, as some of the layers are different color, and it looks like the gradient ends a little early

this is what the design looks like for dark mode vs the current one:
Screenshot 2024-06-02 at 10 28 28 PM
Screenshot 2024-06-02 at 10 31 25 PM

**Review by Aaryan1203 — CHANGES_REQUESTED** [review]
Looks amazing great work! 

I noticed that you pushed up some changes to the yarn lock file which I don't think were intentional so I think you can just revert that!
In order to do that, you can run `git checkout main -- livesite/yarn.lock` which i believe should fix the issue. Its very possible that could break your code and if so we can try to fix that together!

**Review by jmsargent10 — APPROVED** [review]
LGTM after Aaryan's comment is addressed!

**Review by Aaryan1203 — APPROVED** [review]
Great job! LGTM

**Pull request merged**
