### PR TITLE
fix formats

### LINKED ISSUE #15: Update files / folders to follow naming convention discussed
- [ ] Update files / folders to follow naming convention in this [doc](https://docs.google.com/document/d/1qKBZ1l5n0BxYUUEJN15OwFVDD_c8P7tWAICU-yXZ01w/edit)

### PR DESCRIPTION
**Pull request by karynayen**
Fixes #15 

Changelist:
I only found 1 issue with the formatting for the background image, other than that everything looked good! I'm hoping that I'm not missing anything!

### CODE REVIEW

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
looks great!! Could you please also change pageStyles to page-styles inside main-site?

**Review by Dhivas-Sugumar — APPROVED** [review]
LGTM!

**Comment by karynayen** [comment]
> looks great!! Could you please also change pageStyles to page-styles inside main-site?

hmm I think the since the folder is empty, I can't push the changes to github. I could just delete the folder lol

**Comment by jzhzhang66** [comment]
@karynayen sounds good!

**Review by jzhzhang66 — APPROVED** [review]

**Review by mike10911 — APPROVED** [review]
Looks great! LGTM!

**Pull request merged**
