### PR TITLE
Code for conduct

### LINKED ISSUE #26: Code for Conduct
- [x] Create a new code-of-conduct page in the /pages folder inside main site (responsive mobile -> desktop)
- [x] Add code of conduct link on main page so that when clicked it goes to the new page. (See mobile + desktop Figma designs on where it's placed + styling)
Screen Shot 2022-09-28 at 6 33 43 PM
Screen Shot 2022-09-28 at 6 33 55 PM

For the code of conduct page, the design should be the same as the current one at https://hackbeanpot.com/code-of-conduct EXCEPT: 

- [x] There should be no toggle on this page
- [x] The header and footer should be the same as the day mode color
- [x] Background color should be DUNE_PRIMARY
- [x] Text color should be TEXT_BROWN

### PR DESCRIPTION
**Pull request by srazh**
Added Code of Conduct page, linked to main site footer based on the Figma.

Fixes #26

Changelist:

- added code of conduct page 
- linked to footer 

Tested: browser / different device sizes

Screenshots & Screencasts:

Screen Shot 2022-10-04 at 12 00 12 AM
Screen Shot 2022-10-04 at 12 00 32 AM
Screen Shot 2022-10-04 at 12 00 45 AM
Screen Shot 2022-10-04 at 12 00 56 AM

### CODE REVIEW

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
This looks great!! A few comments: 

- Can we give this header some padding so it's not so close to the edge of the screen? Screen Shot 2022-10-04 at 5 39 21 PM
- I feel like from tabletLg and smaller we should just make the paragraph cover the whole width otherwise the paragraph is oddly thin
Screen Shot 2022-10-04 at 5 40 10 PM
- Let's make the header + paragraph aligned here (maybe add your padding to a shared container instead of individually doing it for each part)
Screen Shot 2022-10-04 at 5 41 35 PM

**Review by jzhzhang66 — CHANGES_REQUESTED** [review]
Also please fix merge conflicts before re-requesting review!

**Review by jzhzhang66 — APPROVED** [review]
LGTMMMM

**Review by mike10911 — APPROVED** [review]
Amazing! Great implementation of Judy's comments! LGTM!

**Pull request merged**
